openapi: 3.1.0
info:
  title: Jira Cloud API
  version: 1.0.0
  description: Interact with Jira Cloud to manage issues, epics, comments, and users.
servers:
  - url: https://your-domain.atlassian.net

paths:
  /rest/api/3/issue:
    post:
      operationId: createIssue
      summary: Create a new Jira issue (Story, Epic, Initiative, etc.)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fields:
                  type: object
      responses:
        '201':
          description: Issue created

  /rest/api/3/issue/{issueIdOrKey}:
    get:
      operationId: getIssue
      summary: Get a specific issue by ID or key
      parameters:
        - in: path
          name: issueIdOrKey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Issue details
    put:
      operationId: updateIssue
      summary: Update a Jira issue
      parameters:
        - in: path
          name: issueIdOrKey
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fields:
                  type: object
      responses:
        '204':
          description: Issue updated

  /rest/api/3/issue/{issueIdOrKey}/comment:
    post:
      operationId: addComment
      summary: Add a comment to an issue
      parameters:
        - in: path
          name: issueIdOrKey
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      responses:
        '201':
          description: Comment added

  /rest/api/3/search:
    get:
      operationId: searchIssues
      summary: Search issues using JQL
      parameters:
        - in: query
          name: jql
          required: true
          schema:
            type: string
        - in: query
          name: maxResults
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of matching issues

  /rest/api/3/project:
    get:
      operationId: listProjects
      summary: List all projects
      responses:
        '200':
          description: List of projects

  /rest/api/3/issuetype:
    get:
      operationId: listIssueTypes
      summary: List all issue types (e.g., Story, Task, Bug, Epic, Initiative)
      responses:
        '200':
          description: List of issue types

  /rest/api/3/issue/{issueIdOrKey}/assignee:
    put:
      operationId: assignIssue
      summary: Assign an issue to a user
      parameters:
        - in: path
          name: issueIdOrKey
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
      responses:
        '204':
          description: Assignee updated

  /rest/api/3/user/search:
    get:
      operationId: searchUsers
      summary: Search for a Jira user by name or email
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of matching users
